package com.example.shurtiandroidproject.model

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName
import java.io.Serializable
data class MainModel(@Expose @SerializedName("meals") var meals: List<Meals>)
data class Meals(@Expose @SerializedName("idMeal") var idMeal: String?,
                 @Expose @SerializedName("strMeal") var strMeal: String?,
                 @Expose @SerializedName("strDrinkAlternate") var strDrinkAlternate: String?,
                 @Expose @SerializedName("strCategory") var strCategory: String?,
                 @Expose @SerializedName("strArea") var strArea: String?,
                 @Expose @SerializedName("strInstructions") var strInstructions: String?,
                 @Expose @SerializedName("strMealThumb") var strMealThumb: String?,
                 @Expose @SerializedName("strTags") var strTags: String?,
                 @Expose @SerializedName("strYoutube") var strYoutube: String?,
                 @Expose @SerializedName("strIngredient1") var strIngredient1: String?,
                 @Expose @SerializedName("strIngredient2") var strIngredient2: String?,
                 @Expose @SerializedName("strIngredient3") var strIngredient3: String?,
                 @Expose @SerializedName("strIngredient4") var strIngredient4: String?,
                 @Expose @SerializedName("strIngredient5") var strIngredient5: String?,
                 @Expose @SerializedName("strIngredient6") var strIngredient6: String?,
                 @Expose @SerializedName("strIngredient7") var strIngredient7: String?,
                 @Expose @SerializedName("strIngredient8") var strIngredient8: String?,
                 @Expose @SerializedName("strIngredient9") var strIngredient9: String?,
                 @Expose @SerializedName("strIngredient10") var strIngredient10: String?,
                 @Expose @SerializedName("strIngredient11") var strIngredient11: String?,
                 @Expose @SerializedName("strIngredient12") var strIngredient12: String?,
                 @Expose @SerializedName("strIngredient13") var strIngredient13: String?,
                 @Expose @SerializedName("strIngredient14") var strIngredient14: String?,
                 @Expose @SerializedName("strIngredient15") var strIngredient15: String?,
                 @Expose @SerializedName("strIngredient16") var strIngredient16: String?,
                 @Expose @SerializedName("strIngredient17") var strIngredient17: String?,
                 @Expose @SerializedName("strIngredient18") var strIngredient18: String?,
                 @Expose @SerializedName("strIngredient19") var strIngredient19: String?,
                 @Expose @SerializedName("strIngredient20") var strIngredient20: String?,
                 @Expose @SerializedName("strMeasure1") var strMeasure1: String?,
                 @Expose @SerializedName("strMeasure2") var strMeasure2: String?,
                 @Expose @SerializedName("strMeasure3") var strMeasure3: String?,
                 @Expose @SerializedName("strMeasure4") var strMeasure4: String?,
                 @Expose @SerializedName("strMeasure5") var strMeasure5: String?,
                 @Expose @SerializedName("strMeasure6") var strMeasure6: String?,
                 @Expose @SerializedName("strMeasure7") var strMeasure7: String?,
                 @Expose @SerializedName("strMeasure8") var strMeasure8: String?,
                 @Expose @SerializedName("strMeasure9") var strMeasure9: String?,
                 @Expose @SerializedName("strMeasure10") var sstrMeasure10: String?,
                 @Expose @SerializedName("strMeasure11") var strMeasure11: String?,
                 @Expose @SerializedName("strMeasure12") var strMeasure12: String?,
                 @Expose @SerializedName("strMeasure13") var strMeasure13: String?,
                 @Expose @SerializedName("strMeasure14") var strMeasure14: String?,
                 @Expose @SerializedName("strMeasure15") var strMeasure15: String?,
                 @Expose @SerializedName("strMeasure16") var strMeasuret16: String?,
                 @Expose @SerializedName("strMeasure17") var strMeasure17: String?,
                 @Expose @SerializedName("strMeasure18") var strMeasure18: String?,
                 @Expose @SerializedName("strMeasure19") var strMeasure19: String?,
                 @Expose @SerializedName("strMeasure20") var strMeasure20: String?,
                 @Expose @SerializedName("strSource") var strSource: String?,
                 @Expose @SerializedName("strImageSource") var strImageSource: String?,
                 @Expose @SerializedName("strCreativeCommonsConfirmed") var strCreativeCommonsConfirmed: String?,
                 @Expose @SerializedName("dateModified") var dateModified: String?
                    ):Serializable
